[package]
name = "infoc_client"
version = "0.1.0"
edition = "2021"
authors = ["B83C <b83c@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.6.1"
sysinfo = "0.28.4"
tokio = { version = "1.27.0", features = ["net", "macros", "rt-multi-thread"] }
# windows-sys = { version = "0.48.0", features = ["Win32_System_SystemInformation", "Win32_Foundation", "Win32_System_Diagnostics_Debug"] }
wmi = "0.12.2"
infoc = { path = "../infoc"}

