name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          target: i686-pc-windows-msvc
          override: true
    - uses: actions-rs/cargo@v1
      with:
          use-cross: true
          command: build
          args: --target i686-pc-windows-msvc
    - name: Build
      run: cargo build --verbose -p infoc_server --target i686-pc-windows-msvc
    
    - name: Run tests
      run: cargo test --verbose
